sylius_grid:
    templates:
        action:
            create: "@SyliusUxSemanticUi/grid/action/create.html.twig"
            delete: "@SyliusUxSemanticUi/grid/action/delete.html.twig"
            show: "@SyliusUxSemanticUi/grid/action/show.html.twig"
            update: "@SyliusUxSemanticUi/grid/action/update.html.twig"
            bulkDelete: 
        filter:
            string: "@SyliusUxSemanticUi/grid/filter/string.html.twig"
        bulk_action:
            delete: "@SyliusUxSemanticUi/grid/bulk_action/delete.html.twig"
